class People(Base):
    id = Column(Integer, primary_key=True)
    birth_year = Column(Text)
    eye_color = Column(Text)
    films = Column(Text)
    gender = Column(Text)
    hair_color = Column(Text)
    height = Column(Text)
    homeworld = Column(Text)
    mass = Column(Text)
    name = Column(Text)
    skin_color = Column(Text)
    species = Column(Text)
    starships = Column(Text)
    vehicles = Column(Text)